### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by stelio** [ApsOps/kube-nginx-websocket#2]
Hi Amanpreet

Thanks for the image and instructions. I'm struggling to understand how the nginx-socket proxy should be implemented.

I have my websocket service exposed
* kubectl expose deployment ws-server --port=80 --type=NodePort

And have run the example manifest in this repo, but i'm struggling to understand how this service is exposed via the ELB?

I tried
* kubectl expose service nginx-socket --port=80 --type=LoadBalancer --name=websocket-lb

But started receiving errors like
2018-02-17T06:38:51.486984355Z " while reading PROXY protocol, client: 172.20.77.41, server: 0.0.0.0:8080
2018-02-17T06:38:56.887407301Z 2018/02/17 06:38:56 [error] 8#8: *6332 broken header: "GET /socket.io/?EIO=3&amp;transport=polling&amp;t=M6YVAqT HTTP/1.1

Kind Regards

**Comment by ApsOps** [comment]
@stelio Hi. You would need to enable PROXY protocol on your ELB. Instructions are available here - https://deis.com/blog/2016/socket.io-applications-kubernetes/

**Note: At this point, I suggest checking the official [ingress-nginx#websockets](https://github.com/kubernetes/ingress-nginx#websockets) as well.**

**Comment by stelio** [comment]
Thank you. Much appreciated, ingress-nginx worked a treat.

**Comment by phanindra48** [comment]
Hi @stelio, is it working with multiple pods?
