### ISSUE TITLE
Using on-premise k8 cluster

### ISSUE THREAD

**Issue by mvineza** [ApsOps/kube-nginx-websocket#3]
Hi,

Can I use this method to preserve source IPs in our on-prem kubernetes cluster (running under Rancher 2.X)?

Another difference is that there will no load balancer in front, just a NodePort service waiting for connections.

Regards,
Merrell

**Comment by ApsOps** [comment]
Hi. Sorry for the super late response.

I suggest checking the official [ingress-nginx#websockets](https://github.com/kubernetes/ingress-nginx#websockets). It should work with NodePorts directly.
